# vim:ft=kitty

allow_remote_control yes
listen_on unix:auto

# Unmap Keys
map ctrl+shift+h
map ctrl+shift+j
map ctrl+shift+k
map ctrl+shift+l

# Split window
map cmd+enter launch --bias=50 --location=vsplit --cwd=current 
map cmd+w close_window

# Window Navigator
map cmd+j kitten kittens/pass_keys.py bottom super+j
map cmd+k kitten kittens/pass_keys.py top    super+k
map cmd+h kitten kittens/pass_keys.py left   super+h
map cmd+l kitten kittens/pass_keys.py right  super+l
map cmd+m layout_action bias 90

# Vim Copy
scrollback_pager sh -c 'NVIM_MODE="kitty-copy" vim 63<&0 </dev/null -i NONE -c "au VimEnter * term cat /dev/fd/63 && sleep 100"'
map cmd+e show_scrollback
