# vim:ft=kitty

include fonts.conf
include themes/catppuccin-mocha.conf
include keymaps.conf

window_padding_width 18 18 5 18
hide_window_decorations titlebar-only

window_logo_scale              5
window_logo_alpha              0.25
window_logo_position           top-right

mouse_hide_wait 1.0
cursor none
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 0

cursor_blink_interval 0.5 ease-in-out
confirm_os_window_close 0
dynamic_background_opacity yes
close_on_child_death yes
placement_strategy top-left
enabled_layouts fat:bias=50,stack

