# Genernal
set -g status on
set -g status-justify left
set -g status-interval 1
set -g status-style "bg=default"
set -g status-left ""
set -g status-right ""
set -g window-status-current-format ""
set -g window-status-format ""
set -g window-status-separator ""
set -g status-left-length 150
set -g status-right-length 150

set-hook -g window-layout-changed "run-shell ~/.config/tmux/scripts/status.sh"
set-hook -g pane-focus-in "run-shell ~/.config/tmux/scripts/status.sh"
set-hook -g session-window-changed "run-shell ~/.config/tmux/scripts/status.sh"

set -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g allow-rename on
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -sa terminal-features ',xterm-kitty:RGB'
set -g mouse on



set -g pane-border-style 'fg=#45475a'
set -g pane-active-border-style 'fg=#f9e2af'


# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'


# Keymaps
set -sg repeat-time 0
set-window-option -g mode-keys vi

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix




run '~/.config/tmux/plugins/tpm/tpm'

